/*
  This file was automatically generated by dbt

        Source: models/int_orders__pivoted copy.sql
      Compiled: target/compiled/models/int_orders__pivoted copy.sql
  Last updated: 10/9/2025, 1:06:47 PM
*/

with payments as 
(
    select * from analytics.dbt_jbushspies.stg_payments
    where status = 'success'
)
, pivoted as (
    select 
        order_id, 

        
        
        
            
            sum(case when payment_method = 'bank_transfer' then amount else 0 end) as bank_transfer_amount,
            
            sum(case when payment_method = 'coupon' then amount else 0 end) as coupon_amount,
            
            sum(case when payment_method = 'credit_card' then amount else 0 end) as credit_card_amount,
            
            sum(case when payment_method = 'gift_card' then amount else 0 end) as gift_card_amount,
            
            sum(case when payment_method = 'bitcoin' then amount else 0 end) as bitcoin_amount
    from payments
    group by 1
)
select * from pivoted